import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import { AuthProvider } from '../context/AuthContext'
import { ViewTransitions } from "next-view-transitions";
import { Toaster } from "@/components/ui/sonner"
import { ThemeProvider } from "@/components/ui/themeProvider"
import { MobileSafeAreaTop } from "@/lib/mobileSafeArea";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const pacifico = localFont({
  src: "../fonts/Pacifico-Regular.ttf",
  variable: "--font-pacifico",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({ children }) {
  return (
    <ViewTransitions>
      <html lang="en" suppressHydrationWarning>
        <body
          className={`${geistSans.variable} ${geistMono.variable} ${pacifico.variable} antialiased text-foreground overflow-hidden bg-gradient-to-b from-primary-lite/50 from-40% to-background to-60%`}
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <AuthProvider>
                {children}
                <Toaster gap={10} position="top-center" richColors/>
            </AuthProvider>
          </ThemeProvider>
        </body>
      </html>
    </ViewTransitions>
  );
}
