import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import { AuthProvider } from '../context/AuthContext'
import { ViewTransitions } from "next-view-transitions";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const pacifico = localFont({
  src: "../fonts/Pacifico-Regular.ttf",
  variable: "--font-pacifico",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({ children }) {
  return (
    <ViewTransitions>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} ${pacifico.variable} antialiased text-foreground overflow-hidden`}
        >
          <AuthProvider>
            {children}
          </AuthProvider>
        </body>
      </html>
    </ViewTransitions>
  );
}
